name: mi_card
description: A Flutter business card application.


version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/dchad.png

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf

